---
title: "00-ShinyTemplate"
author: "Jerry Davis"
date: "11/15/2021"
output: html_document
runtime: shiny
---

## Template

```{r}
library(shiny)
ui <- fluidPage()
server <- function(input, output){}
shinyApp(ui = ui, server = server)
```

## An input added:

```{r}
library(shiny)
ui <- fluidPage(
  inputPanel(
  selectInput("n_breaks", label = "Number of bins:",
              choices = c(10, 20, 35, 50), selected = 20),
  
  sliderInput("bw_adjust", label = "Bandwidth adjustment:",
              min = 0.2, max = 2, value = 1, step = 0.2)
  ),
  plotOutput(outputId = "hist")
)
server <- function(input, output){
  output$hist <- renderPlot({
    hist(rnorm(input$n))
 })
}
shinyApp(ui = ui, server = server)
```

## An output added:

```{r}
library(shiny)
ui <- fluidPage(
  inputPanel(
  selectInput("n_breaks", label = "Number of bins:",
              choices = c(10, 20, 35, 50), selected = 20),
  
  sliderInput("bw_adjust", label = "Bandwidth adjustment:",
              min = 0.2, max = 2, value = 1, step = 0.2)
  ),
  plotOutput(outputId = "hist")
)
server <- function(input, output){
output$hist <- renderPlot({
  hist(faithful$eruptions, probability = TRUE, breaks = as.numeric(input$n_breaks),
       xlab = "Duration (minutes)", main = "Geyser eruption duration")
  
  dens <- density(faithful$eruptions, adjust = input$bw_adjust)
  lines(dens, col = "blue")
}) 
}
shinyApp(ui = ui, server = server)
```

